# Use an official Node.js runtime as a parent image
FROM node:14-alpine AS build

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy the rest of the application files to the working directory
COPY . .

# Build the application
RUN npm run build

# Use an official Nginx runtime as a parent image
FROM nginx:1.21-alpine

# Copy the built application from the previous stage to the Nginx image
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the Nginx configuration file to the Nginx image
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]




# FROM node:14-alpine AS build
# WORKDIR /app

# COPY package*.json ./
# RUN npm install
# COPY . .
# # RUN npm start
# CMD [ "node", "index.js" ]

# FROM nginx

# RUN apt-get update && apt-get upgrade -y

# COPY nginx.conf /etc/nginx/nginx.conf
# RUN service nginx restart

# # EXPOSE 80
# ENTRYPOINT ["nginx", "-g", "daemon off;"]