
FROM node:14-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
# RUN npm start
# CMD [ "node", "index.js" ]

FROM nginx

RUN apt-get update && apt-get upgrade -y

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]